DRESS = 1
JEANS = 2
SKIRT = 3
BLOUSE = 4
CLOTHES = (
    (DRESS, 'DRESS'),
    (JEANS, 'JEANS'),
    (SKIRT, 'SKIRT'),
    (BLOUSE, 'BLOUSE')
)

SERVICE1 = 1
SERVICE2 = 2
SERVICE3 = 3
SERVICE = (
    (SERVICE1, 'SERVICE1'),
    (SERVICE2, 'SERVICE2'),
    (SERVICE3, 'SERVICE3')
)
