# Generated by Django 2.2.5 on 2019-11-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190929_0900'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='block',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
